name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *" # 10분마다 실행 (UTC 기준)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render API
        run: curl -s https://stockus-be.onrender.com/ping
