name: Daily Scrape and Summary

on:
  schedule:
    - cron: "50 12 * * *"
  workflow_dispatch:  # 수동 실행도 가능하게!

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create credentials json
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" | base64 --decode > stock-project-456213-00f766c38980.json

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3
      
      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Run scrap
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: poetry run python scrap.py # poetry로 실행
